app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns =[
    path('sthree/',sthree,name='sthree'),
]

project14/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import *
import app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('one/',one,name='one'),
    path('two/',two,name='two'),
    path('app2/',include('app2.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def one(request):
    return render(request,'one.html')

def two(request):
    return render(request,'two.html')

app2/views.py
import re
from django.shortcuts import render

# Create your views here.
def sthree(request):
    return render(request,'sthree.html')

templates/one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>one html file</title>
    <style>
        body
        {
            color: blue;
            background-color: cyan;
        }
    </style>
</head>
<body>
    <center>
        <h1>Hello this is one project html file</h1>
    </center>
    <h2>conn to two html file</h2>
    <a href="{% url 'two'%}">if you click on this it will go to two html file</a>
    <center>
        <h1>conn to specific html file</h1>
        <a href="{% url 'app2:sthree'%}">if you click on this it will go to specific html file </a>
    </center>
</body>
</html>

templates/sthree.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body
        {
            color: blue;
            background-color: cyan;
        }
    </style>
</head>
<body>
    <center>
        <h1> Hello this is my sthree project html file</h1>
    </center>
    <h2>conn to one html file</h2>
    <a href="{% url 'one'%}">if you click on this it will go to one html file</a>
    <center>
        <h2>conn to TWO html file</h2>
        <a href="{% url 'two'%}">if you click on this it will go to two html file</a>
    </center>
</body>
</html>

templates/two.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>two html file</title>
    <style>
        body
        {
            color: blue;
            background-color: cyan;
        }
    </style>
</head>
<body>
    <center>
        <h1>Hello this is my two project html file</h1>
    </center>
    <h2>conn to one html file</h2>
    <a href="{% url 'one'%}">if you click on this it will go to one html file</a>
    
    <center>
        <h1>conn to specific html file</h1>
        <a href="{% url 'app2:sthree'%}">if you click on this it will go to specific html file </a>
    </center>
    
</body>
</html>